### ISSUE TITLE
Reinstate E2E tests in CI

### ISSUE THREAD

**Issue by plumdog** [Flagsmith/flagsmith-charts#100]
Verified broken (brittle) in #98. Removed in #99.

Fix them and reinstate.

**Comment by matthewelwell** [comment]
This should be possible now following what we have in our main open source repository here: 

A [docker compose file](https://github.com/Flagsmith/flagsmith/blob/main/frontend/docker-compose-e2e-tests.yml) for running the tests in a self contained environment.

A [workflow](https://github.com/Flagsmith/flagsmith/blob/main/.github/workflows/platform-pull-request.yml#L44) exhibiting how this can run in a Github Action.

The E2E image is also published [here](https://hub.docker.com/repository/docker/flagsmith/flagsmith-e2e-tests/general) so can be used without having to build the image itself.
