### ISSUE TITLE
configuring saml SSO via env variables

### ISSUE THREAD

**Issue by alikhil** [Flagsmith/flagsmith-charts#112]
Hello!

Is it possible to configure SAML SSO only using environment variables?

**Comment by dabeeeenster** [comment]
We don't provide SAML authentication in our open source version I'm afraid. If you want to get in touch with our team via https://flagsmith.com/contact-us/ we can discuss enterprise options. Thanks!

**Comment by alikhil** [comment]
According to [documentation](https://docs.flagsmith.com/deployment/authentication). SAML is available in opensource version.

@dabeeeenster please reopen this ticket

**Comment by dabeeeenster** [comment]
Hi @alikhil - I've updated the docs to clarify SAML is enterprise only.
