### ISSUE TITLE
Deployed Helm chart but api pod is failing to start... no useful error message to go on:(

### ISSUE THREAD

**Issue by brandoncollins7** [Flagsmith/flagsmith-charts#147]
![image](https://github.com/Flagsmith/flagsmith-charts/assets/36413482/8bdfb744-ffb8-42d5-8c15-279c0db10dac)

**Comment by matthewelwell** [comment]
@brandoncollins7 please can you provide as much information about your deployment environment as you can? Helm chart version, application version. If possible, please provide your `values.yaml` file so we can attempt to investigate / replicate.

**Comment by gagantrivedi** [comment]
Feel free to reopen with the above information if it is still an issue
