### ISSUE TITLE
Deployed helm chart to kubernetes. Api pod fails to start. No error message to work with:(

### ISSUE THREAD

**Issue by brandoncollins7** [Flagsmith/flagsmith-charts#148]
![image](https://github.com/Flagsmith/flagsmith/assets/36413482/ba10a94a-17d9-4d91-95f7-1a69aa185a3c)

**Comment by brandoncollins7** [comment]
I am using latest. Simply followed these steps on the docs page:

helm repo add flagsmith https://flagsmith.github.io/flagsmith-charts/
helm install -n flagsmith --create-namespace flagsmith flagsmith/flagsmith

I believe it has something to do with not finding a database. Looks like there wasn't any postgres deployed?

**Comment by khvn26** [comment]
Hello @brandoncollins7! Just tried reproducing by running the exact commands you provided. I did get the `Error from server (BadRequest): container "flagsmith-api" in pod "flagsmith-fresh-test-api-87d8745c6-q4nqj" is waiting to start: PodInitializing` message while the API pod was initializing, but it eventually was up and running, just as expected.

If your API pod is stuck in this state, this means the init containers take too much time to run. To check the status of init containers, please select the `wait-for-db`/`migrate-db` container in your UI or use the following commands:

```bash
kubectl logs flagsmith-api-d4871 -c wait-for-db 
kubectl logs flagsmith-api-d4871 -c migrate-db 
```

**Comment by khvn26** [comment]
@brandoncollins7 We didn't hear back from you so I'm closing this issue. Feel free to come back with details and we'll reopen it should we reproduce a problem.
