### ISSUE TITLE
Support for injection of extra containers

### ISSUE THREAD

**Issue by nick-jones** [Flagsmith/flagsmith-charts#149]
We'd like to pull metrics from our flagsmith instance. We use prometheus internally which, as far as I know, flagsmith does not natively support via scrape endpoints. Flagsmith does support StatsD, however - https://docs.flagsmith.com/deployment/hosting/locally-api#statsd-integration

So, what I'd like to do is run https://github.com/prometheus/statsd_exporter - this can act like a StatsD server, and expose prometheus style metrics. The recommended way to run this is as a sidecar - so the flagsmith `STATSD_HOST` api env var would be configured as `localhost`.

Unfortunately with the current helm charts, there is no way to inject additional containers (that I can see, at least). I've seen other helm charts support `extraContainers` and `extraInitContainers` - I'm curious if there might be a possibility to add support for these here?

**Comment by khvn26** [comment]
Hi @nick-jones! That's a great proposal. Feel free to bring in a PR implementing this. Otherwise we'll be sure to plan and execute this in the foreseeable future as it doesn't seem like a taxing change.
