### ISSUE TITLE
 Upgrade the chart to support the latest version of Flagsmith

### ISSUE THREAD

**Issue by civilizeddev** [Flagsmith/flagsmith-charts#152]
First, I would like to express my gratitude for the efforts of the maintainers.

My company needed feature flag functionality, so I was weighing between flipt.io and Flagsmith and ended up self-hosting Flagsmith on our company's k8s.

However, there were unresolved minor bugs and structural issues that couldn't be solved by simply changing the image tag version to the latest, and it was significantly behind the latest version of Flagsmith.

I waited for the Flagsmith chart to be upgraded, but in the meantime, the direction shifted towards using flipt.io in my team, and I ended up being someone who made the team wait in vain without contributing anything. Unfortunately, this means Flagsmith missed a potential user. Perhaps if Flagsmith had been adopted, it could have been widely promoted, which is a bit regrettable.

Please upgrade the chart quickly going forward.

**Comment by dabeeeenster** [comment]
Hi @civilizeddev - thanks for the feedback! We will make a regular task to update the version. You can also update the `AppVersion` in your helm config?
