### ISSUE TITLE
Ability to add labels and annotations to all resources in helm chart

### ISSUE THREAD

**Issue by masmontanas** [Flagsmith/flagsmith-charts#159]
It would be very helpful to expose a configuration for `commonLabels` and `commonAnnotations` in the helm chart so users can set labels and annotations on all resources created by the helm chart in one place.

We currently have some integration use-cases that require certain labels/annotations exist on all resources associated with a helm chart, and the pattern above is quite common for other helm charts in the k8s ecosystem.

We'd be happy to put in the PR ourselves if the maintainers agree with the pattern above.

Thanks!

**Comment by matthewelwell** [comment]
Hi @masmontanas, yes - this sounds like a good idea, we'd be more than happy to receive a PR on this. 

It would be great if you could also submit a matching PR to update the documentation on our [main repository](https://github.com/flagsmith/flagsmith) too.

**Comment by masmontanas** [comment]
Thanks @matthewelwell , our team will put in a PR for this likely tomorrow.

**Comment by danielloader** [comment]
@matthewelwell is this still outstanding?

**Comment by matthewelwell** [comment]
Sorry, no - this should have been closed. See the PR [here](https://github.com/Flagsmith/flagsmith-charts/pull/162).
