### ISSUE TITLE
Add `extraEnv` for taskProcessor service

### ISSUE THREAD

**Issue by matthewelwell** [Flagsmith/flagsmith-charts#168]
Similar to the `extraEnv` attribute defined for the `api` service (see [here](https://docs.flagsmith.com/deployment/hosting/kubernetes#environment-variables)), it should be possible to define `extraEnv` for the taskProcessor service. 

We may need to consider how this affects current users of the charts, however, since the current behaviour is that the `api.extraEnv` gets written to the environment variables of the taskProcessor. Initially we should maintain this behaviour and write both `api.extraEnv` and `taskProcessor.extraEnv` to the taskProcessor environment variables but ideally we would deprecate the `api.extraEnv` from being used by the taskProcessor service.

**Comment by Arvind644** [comment]
Hii @matthewelwell I want to work on this issue. Can you give me more details for this issue.

**Comment by matthewelwell** [comment]
@Arvind644 Great! I have updated the description, let me know if you need more information.

**Comment by Arvind644** [comment]
@matthewelwell  Thanks a lot. I will start working on this issue now. Will ask you if I had any doubt.
