### ISSUE TITLE
Allow specifying topologySpreadConstraints in chart output

### ISSUE THREAD

**Issue by rolodato** [Flagsmith/flagsmith-charts#291]
Consider if we need to support a dedicated section for this, or if we can supply arbitrary modifications to the spec

![Image](https://github.com/user-attachments/assets/dff28f8b-270c-40d3-9b9e-7e9a7bb69881)

**Comment by khvn26** [comment]
Released in https://github.com/Flagsmith/flagsmith-charts/releases/tag/flagsmith-0.60.0
