### ISSUE TITLE
Configure Environment ENV prod

### ISSUE THREAD

**Issue by Dionizioaf** [Flagsmith/flagsmith-charts#36]
I installed the flagsmith in kubernetes and have everything working, but when i access the url it show in the butterbar the message **" You are using the develop environment. "**

I configure the Extraenv : DEV: 'prod' and during helm install i set debug and it shows the Environment variable is being created, but the message don't disappear.

Can anyone help me what i need to do to remove this message?

**Comment by Dionizioaf** [comment]
Im using EKS with ELB 

**values.yaml**
api:
  image:
    repository: flagsmith/flagsmith-api
    tag: null  # defaults to .Chart.AppVersion
    imagePullPolicy: IfNotPresent
    imagePullSecrets: []
  replicacount: 1
  podAnnotations: {}
  resources: {}
  # limits:
  #   cpu: 500m
  #   memory: 500Mi
  # requests:
  #   cpu: 300m
  #   memory: 300Mi
  podLabels: {}
  extraEnv: 
    ENV: 'prod'
  nodeSelector: {}
  tolerations: []
  affinity: {}
  podSecurityContext: {}
  defaultPodSecurityContext:
    enabled: true
    # runAsNonRoot: true  # TODO: enable this, conditional on tag semver
    # runAsUser: 1000
    # runAsGroup: 1000
  livenessProbe:
    failureThreshold: 5
    initialDelaySeconds: 5
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 2
  readinessProbe:
    failureThreshold: 10
    initialDelaySeconds: 1
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 2
  dbWaiter:
    image:
      repository: willwill/wait-for-it
      tag: latest
      imagePullPolicy: IfNotPresent
    timeoutSeconds: 30

frontend:
  enabled: true
  image:
    repository: flagsmith/flagsmith-frontend
    tag: null  # defaults to .Chart.AppVersion
    imagePullPolicy: IfNotPresent
    imagePullSecrets: []
  replicacount: 1
  resources: {}
  # limits:
  #   cpu: 500m
  #   memory: 500Mi
  # requests:
  #   cpu: 300m
  #   memory: 300Mi
  apiProxy:
    enabled: true
  extraEnv: 
    ENV: 'prod'
  nodeSelector: {}
  tolerations: []
  affinity: {}
  podSecurityContext: {}
  defaultPodSecurityContext:
    enabled: true
    # runAsNonRoot: true  # TODO: enable this, conditional on tag semver
    # runAsUser: 1000
    # runAsGroup: 1000
  livenessProbe:
    failureThreshold: 20
    initialDelaySeconds: 20
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 10
  readinessProbe:
    failureThreshold: 20
    initialDelaySeconds: 20
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 10

postgresql:
  enabled: true
  serviceAccount:
    enabled: true
  nameOverride: flagsmith-postgresql
  postgresqlDatabase: flagsmith
  postgresqlUsername: postgres
  postgresqlPassword: flagsmith

databaseExternal:
  enabled: false
  url: null
  type: postgres
  host: null
  port: 5432
  database: null
  username: null
  password: null
  urlFromExistingSecret:
    enabled: false
    name: null
    key: null

influxdb:
  enabled: true
  nameOverride: influxdb
  image:
    repository: quay.io/influxdb/influxdb
    tag: v2.0.2
    imagePullPolicy: IfNotPresent
    imagePullSecrets: []
  adminUser:
    organization: "influxdata"
    bucket: "default"
    user: "admin"
    # Leave empty to generate a random password and token.
    # Or fill any of these values to use fixed values.
    password: ""
    token: ""
  persistence:
    enabled: false
    # name: influxdb-pvc
    # storageClass: "-"
    # accessMode: ReadWriteOnce
    # size: 50Gi
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

influxdbExternal:
  enabled: false
  url: null
  bucket: null
  organization: null
  token: null
  tokenFromExistingSecret:
    enabled: false
    name: null
    key: null

service:
  influxdb:
    externalPort: 8080
  api:
    type: ClusterIP
    port: 8000
  frontend:
    type: ClusterIP
    port: 8080

ingress:
  frontend:
    enabled: true
    annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    hosts:
      - host: flagsmith.mydomain.com
        paths: [
          /
        ]
    tls: []
  api:
    enabled: true
    annotations: {}
    hosts:
      - host: flagsmith-api.mydomain.com
        paths: [
          /api,
          /health
        ]
    tls: []

**Comment by dabeeeenster** [comment]
Have a look here: https://docs.flagsmith.com/deployment/overview#running-flagsmith-on-flagsmith
