### ISSUE TITLE
Add some testing around the Github Action

### ISSUE THREAD

**Issue by dabeeeenster** [Flagsmith/flagsmith-charts#40]
We should be implementing some targets as part of `helm test` that are run by `ct install`

**Comment by dabeeeenster** [comment]
There is an E2E test that brings up the back end and front end and then runs chromedriver across a bunch of tests - see this action:

https://github.com/Flagsmith/flagsmith/blob/31ba88fff160027653841b1789a52d85df3aba50/.github/workflows/platform-pull-request.yml#L40

It would be good to replicate something like this in a similar action but running the infra in helm/k8s as opposed to manually as in the action above.

**Comment by matthewelwell** [comment]
Discussed with @plumdog and @dabeeeenster that it would be good to build an image for the frontend component that includes everything necessary to run the E2E tests, e.g. chrome, npm dev dependencies, and push it to dockerhub under a new tag (e.g. flagsmith-e2e-testing). 

Seems like this shouldn't be too hard. Thoughts @kyle-ssg ?
