### ISSUE TITLE
storageClass

### ISSUE THREAD

**Issue by ahmadgh9** [Flagsmith/flagsmith-charts#64]
Hi
I cant define specific strorage class for postgreSQL pvc

**Comment by dabeeeenster** [comment]
Hi There,

Sorry - we need more info here! Can you describe in more detail the issue?

**Comment by ahmadgh9** [comment]
Hi
in this chart i can not specify the storageClass for PVC that postgreSQL is using
postgre values : 
`
global:
  postgresql: {}
#   imageRegistry: myRegistryName
#   imagePullSecrets:
#     - myRegistryKeySecretName
#   **storageClass: myStorageClass**
`

**Comment by dabeeeenster** [comment]
Ah understood. We would be happy to take pull requests for this - being honest this would not be a priority for us right now but we will get to it at some point!

**Comment by plumdog** [comment]
Hi @ahmadgh9, you can set the storage class for the in-cluster Postgres in either of the following ways:
```yaml
global:
  storageClass: mystorageclass
```
or
```yaml
postgresql:
  persistence:
    storageClass: mystorageclass
```
Using the second method, you can set any value that the Postgres chart understands, see all options here https://github.com/helm/charts/blob/master/stable/postgresql/values.yaml

**Comment by plumdog** [comment]
Just to demonstrate this a different way:
```
$ helm repo add flagsmith https://flagsmith.github.io/flagsmith-charts/
"flagsmith" has been added to your repositories
$ helm template flagsmith/flagsmith --set global.storageClass=mystorageclass | grep -C 3 mystorageclass                
        resources:
          requests:
            storage: "8Gi"
        storageClassName: mystorageclass
$ helm template flagsmith/flagsmith --set postgresql.persistence.storageClass=mystorageclass | grep -C 3 mystorageclass
        resources:
          requests:
            storage: "8Gi"
        storageClassName: mystorageclass
```
