### ISSUE TITLE
Feature Request: add annotations to Service objects

### ISSUE THREAD

**Issue by ncalibey** [Flagsmith/flagsmith-charts#65]
Hi there! I was wondering if it would be possible to template the annotations applied to the `flagsmith-frontend` and `flagsmith-api` Services? We utilize annotations in our set up to work with external DNS, and I'd rather not have to write a script to apply them personally on a new deployment. If it would help, I would gladly submit a PR adding them. Thanks!

**Comment by dabeeeenster** [comment]
That would be a great improvement @ncalibey !
