### ISSUE TITLE
Flagsmith-on-Flagsmith not working when self-hosting

### ISSUE THREAD

**Issue by ncalibey** [Flagsmith/flagsmith-charts#67]
Hi there,

Just had a question about setting up Flagsmith-on-Flagsmith. It seems that even though I have set up both the `FLAGSMITH_ON_FLAGSMITH_API_URL` and `FLAGSMITH_ON_FLAGSMITH_API_KEY` variables correctly (verified both by inspecting the k8s Pods as well as in the console), every request to the API server for `/flags` or `/flags/analytics` just hangs. When I first open up the front-end app I can still log in, make changes, etc., but none of the custom features I want are coming back (e.g. when calling `flagsmith.getValue('oauth_google'`) I just get `null` instead of the expected string). After a few hard refreshes there's nothing but the spinning loading modal.

If I remove the relevant environment variables, then everything works, but then we can't run Flagsmith-on-Flagsmith.

Any ideas of what could be going on and why the requests are just hanging? The only logs I'm getting from the API server is `app.views    WARNING  FE assets do not exist, ignoring and returning HTTP 200.`. The result is the same when I try to curl it as well.

Extra frontend environment variables:
- `API_URL`: `<api_url>/api/v1/`
- `FLAGSMITH_API_URL`: `<api_url>/api/v1/`
- `FLAGSMITH_ON_FLAGSMITH_API_URL`: `<api_url>/api/v1/`
- `FLAGSMITH_ON_FLAGHSMITH_API_KEY`: `key_from_project`
- `ENABLE_INFLUXDB_FEATURES: 0`

Extra backend environment variables:
- `LOG_LEVEL: DEBUG` (this is in our dev environment)
- `DJANGO_CSRF_TRUSTED_ORIGINS:` `<origin_our_dashboard_is_under>`

Thank you!

**Comment by dabeeeenster** [comment]
Are you able to provide the URLs that are being called with the FoF requests are being made? 

By default the front end proxies requests to the API in Kuberenetes - is the API node publicly accessible?

**Comment by ncalibey** [comment]
Hi Ben,

The API server URL is `https://<api-url>/api/v1/flags/` (have to "blot out" the main domain since it's internal for our team). The calls to it work when FoF is disabled, but they hang when it's on. The API node is publicly accessible as it's a `NodePort`.

**Comment by dabeeeenster** [comment]
Can you provide 2 `curl` examples - one that works and one that fails - obscuring the domain names?

**Comment by ncalibey** [comment]
@dabeeeenster sorry for the delay, but it seems the issue was related to how we had our ingress set up. We got it working now -- I'll go ahead and close this issue. Thanks again for the responses!

**Comment by dabeeeenster** [comment]
Grea thanks!
