### ISSUE TITLE
Selfhost without Email

### ISSUE THREAD

**Issue by FischlerA** [Flagsmith/flagsmith-charts#68]
Hi, 
i'm currently trying to get Flagsmith up and running inside of our kubernetes cluster. 
The Deployment is working just fine, the only issue is, as soon as i try to access a feature flag the configuration window immediately closes.

The logs contain the following error:
`django.core.exceptions.ImproperlyConfigured: 
                SENDGRID_API_KEY must be declared in settings.py`

In my understanding this settings is required for sending Emails.

According to the documentation https://docs.flagsmith.com/deployment/locally-api#email-environment-variables it should be possible to run Flagsmith selfhosted without email, what Environment Variables need to be set/configured for this to work?

**Comment by FischlerA** [comment]
Further investigation showed, that the configuration of the email has nothing to do with the feature flag configuration window immediately disappearing, but i'm still looking into it.

**Comment by maxisam** [comment]
FYI, you can set EMAIL_BACKEND: django.core.mail.backends.smtp.EmailBackend 

https://docs.flagsmith.com/deployment/locally-api#environments-with-no-direct-console-access-eg-heroku-ecs

**Comment by plumdog** [comment]
Hi @FischlerA, are you happy for this issue to be closed? From having read the above, am I right that there is an outstanding issue, but it is tracked by https://github.com/Flagsmith/flagsmith/issues/340 instead?

**Comment by FischlerA** [comment]
Hi @plumdog yes, as far as i am aware this issue can be closed.
