### ISSUE TITLE
Api only deployment

### ISSUE THREAD

**Issue by maxisam** [Flagsmith/flagsmith-charts#69]
https://github.com/Flagsmith/flagsmith-charts/blob/354101c87892c7fd6decec5d9a197ec09cb4d067/charts/flagsmith/values.yaml#L56

It turns out this doesn't work. There is no api only deployment

**Comment by dabeeeenster** [comment]
Are you able to provide more detail here? What exactly doesnt work? What are the steps to reproduce?

**Comment by maxisam** [comment]
If I want to deploy API only, it will deploy frontend as well. Line 56 doesn't really do anything. It wasn't used in the template at all.
