### ISSUE TITLE
E2E testing: use Chrome instead of (or as well as) Firefox

### ISSUE THREAD

**Issue by plumdog** [Flagsmith/flagsmith-charts#87]
Knock-on from #78. Might be low priority, or not wanted at all.

Found that Firefox would run in the kind cluster in the Github Action, but Chrome wouldn't. Work out why and use Chrome instead (or as well?).

**Comment by matthewelwell** [comment]
Closing on account of the fact this was only needed for the previous 'monster' implementation. Now that we are using the E2E testing container, this is no longer a concern.
