### ISSUE TITLE
Seed admin user on deploy

### ISSUE THREAD

**Issue by BestLSJ** [Flagsmith/flagsmith-charts#96]
Add a REST `POST` endpoint that achieves the same functionality as  `/api/v1/users/config/init/` after deployment. This will make it easier to automate deployments.

**Comment by dabeeeenster** [comment]
Hi @BestLSJ  - I'm not sure how else you would achieve this? The call to `init` is there to seed the user?

**Comment by BestLSJ** [comment]
Hi @dabeeeenster

Thanks for your quick reply.

I'm working on a way to deploy flagsmith fully automatically, and I can't seem find a way to seed the admin user without visiting `init` manually a browser.

I'd like a way to do this more programmatically, and having it as part of the flagsmith helm chart just seemed intuitive.

**Comment by dabeeeenster** [comment]
Ah interesting point. Would a REST interface to do this achieve what you are looking for?

**Comment by BestLSJ** [comment]
I guess it would.

**Comment by dabeeeenster** [comment]
>  it would be greatly appreciated if there was a simpler way.

How could we make it simpler?

**Comment by BestLSJ** [comment]
> How could we make it simpler?

First you have to make a get request to get the `csrfmiddlewaretoken` and you have to extract this token from an html response. In principle you could make an endpoint to just get the token, or remove the need for the token all together. 

Furthermore documenting the `POST` request would also greatly help. I had to use fiddler and decrypt the http requests to figure out the formatting schema. And only by being lucky with an error message did I learn needed the `Referer` header as well.

**Comment by francoisauclair911** [comment]
Also this helm chart apparently implements such feature, so maybe that can be used as inspiration 
https://github.com/one-acre-fund/oaf-public-charts/blob/main/charts/flagsmith/templates/api-deploy.yaml

Alternatively we could have a section in the template to run `commands` and use this to seed a new admin user

**Comment by matthewelwell** [comment]
Related PR: https://github.com/Flagsmith/flagsmith/pull/2205
